config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    post 'activate' => 'orders#activate', as: :activate
    post 'archive' => 'orders#archivate', as: :archivate

    member do
      get 'check_list' => 'documents#check_list', as: :check_list
      get 'service_list' => 'documents#service_list', as: :service_list
      get 'flowers' => 'documents#flowers', as: :flowers
      get 'cremazione' => 'documents#cremazione', as: :cremazione
      get 'epigrafe' => 'documents#epigrafe', as: :epigrafe
      get 'mod_commis' => 'documents#mod_commis', as: :mod_commis
    end

  end
  resources :documents, only: [:index]
  resources :relatives, as: :contacts, only: [:index]

  root 'orders#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :deceased, autosave: true, dependent: :destroy, touch: true
  belongs_to :relative, autosave: true, dependent: :destroy, touch: true
  belongs_to :document, autosave: true, dependent: :destroy, touch: true
  belongs_to :cemetery, autosave: true, dependent: :destroy, touch: true
  belongs_to :crematorium, autosave: true, dependent: :destroy, touch: true
  belongs_to :epigraph, autosave: true, dependent: :destroy, touch: true
  has_many :flowers, dependent: :destroy
  has_many :assistants
  has_many :cars

  accepts_nested_attributes_for :cars, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :assistants, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :flowers, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :deceased, :update_only => true
  accepts_nested_attributes_for :relative, :update_only => true
  accepts_nested_attributes_for :document, :update_only => true
  accepts_nested_attributes_for :cemetery, :update_only => true
  accepts_nested_attributes_for :crematorium, :update_only => true
  accepts_nested_attributes_for :epigraph, :update_only => true

  validates :relative, presence: true
  validates :deceased, presence: true
  validates :document, presence: true
  validates :cemetery, presence: true
  validates :crematorium, presence: true
  validates :epigraph, presence: true

 # validates :fiscal_code, length: {maximum: 16}

  enum :docs_kind => [:check_list, :service_list, :flowers, :cremazione, :epigrafe, :mod_commis]
  enum :status => [:active, :archived]

  scope :full, -> { includes(:deceased, :relative, :flowers, :assistants, :cars, :epigraph, :document, :cemetery, :crematorium) }
  scope :part, -> { includes(:deceased, :relative) }

  scope :ordered, -> { order(:updated_at).reverse_order }
  scope :ordered_name, -> { part.order('deceaseds.lastname') }
  scope :ordered_relative, -> { part.order('relatives.lastname') }

  scope :active, -> { where('status=?', 0) }
  scope :archived, -> { where('status=?', 1) }

  def splitted_fiscal_code
    self[:fiscal_code].split(//)
  end

  def edited_at
    self[:updated_at].strftime(('%H:%M %d %b, %Y'))
  end

  def self.search(query)
    if query
      part.joins(:deceased, :relative).where('deceaseds.firstname like ? or deceaseds.lastname like ? or relatives.firstname like ? or relatives.lastname like ?', "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%")
    else
      part
    end
  end

end

app/controllers/orders_controller.rb
require 'gon'

class OrdersController < ApplicationController

  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :set_gon_vars, only: [:new, :edit]

  # GET /orders
  # GET /orders.json
  def index
    @order_by = params[:order]
    @query = params[:query]
    @orders =  Order.search(@query)
    if params[:archived].present?
      @orders = @orders.archived
    else
      @orders = @orders.active
    end
    if @order_by.present?
      if @order_by == t('labels.relative')
        @orders = @orders.ordered_relative
      elsif @order_by == t('labels.name')
        @orders = @orders.ordered_name
      elsif @order_by ==t('labels.updated')
        @orders = @orders.ordered
      end
    end
    @reverse = params[:reverse]
    if @reverse.present?
      @orders = @orders.reverse_order
    end
    @page = params[:page] || 1
    @orders = @orders.paginate(:page => @page, :per_page => 8)
    view = params[:view]
    if view.present?
      @view = view
    else
      @view = t('labels.card')
    end



    respond_to do |format|
      format.html
      format.json
      format.js
    end

  end

  # GET /orders/1
  # GET /orders/1.json
  def show

  end

  # GET /orders/new
  def new
    @order = Order.new
    @order.build_deceased
    @order.build_relative
    @order.build_document
    @order.build_cemetery
    @order.build_crematorium
    @order.build_epigraph
    @order.flowers.build
    @order.assistants.build
    @order.cars.build
  end

  # GET /orders/1/edit
  def edit

  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
        format.js { render 'orders/show/note', locals: { msg: 'Success update!', key: 'success' } }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
        format.js { render 'orders/show/note', locals: { msg: 'Something goes wrong!', key: 'error' } }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def archivate
    @order = Order.part.find(params[:order_id])
    @order.status = :archived
    if @order.save!
      redirect_to @order, notice: 'Order was successfully archived.'
    else
      render :json => false
    end

  end

  def activate
    @order = Order.part.find(params[:order_id])
    @order.status = :active
    if @order.save!
      redirect_to @order, notice: 'Order was successfully activated.'
    else
      render :json => false
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.full.find(params[:id])
    end

    def set_gon_vars
      @funeral_places = Hash[Deceased.funeral_places.map{|x| [x, nil]}]
      gon.funeral_places = @funeral_places
      @cemetery_names = Hash[Deceased.cemetery_names.map{|x| [x, nil]}]
      gon.cemetery_names = @cemetery_names
      @relationships = Hash[Relative.relationships.map{|x| [x, nil]}]
      gon.relationships = @relationships
      @coffin_kinds = Hash[Deceased.coffin_kinds.map{|x| [x, nil]}]
      gon.coffin_kinds = @coffin_kinds
      @dedicates = Hash[Epigraph.dedicates.map{|x| [x, nil]}]
      gon.dedicates = @dedicates
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:id, :status, :operation_1, :operation_2,  :operation_3,  :operation_4,  :operation_5,  :operation_6,  :operation_7,  :note, :flower_note, :service_note, :fiscal_code,
                                    :deceased_attributes => [:firstname, :lastname, :birthday,
                                                             :deathday, :deathtime, :funeral_day, :funeral_place,
                                                             :crematorium_kind, :photo, :cemetery_name,
                                                             :funeral_time, :born_place, :death_place, :vase_issued_by,
                                                             :applicant,  :fax_mail, 
                                                             :coffin_kind, :flowerday, :flowertime,
                                                             :coffin_prepare_by, :coffin_issued_by, :note,
                                                             :exposure_day, :morgue_work_from, :morgue_work_to,
                                                             :departure_day, :departure_time, :pillow_take,
                                                             :instruments_1, :instruments_2, :instruments_3,
                                                             :instruments_4, :information_1, :information_2,
                                                             :registered_in, :registered_in_address,
                                                             :profession, :marital_status, :corpse_kind, 
                                                             :arrive_day, :arrive_time, :invoice_company,
                                                             :invoice_place, :invoice_street, :invoice_house, 
			             :lastname_declar, :fistname_declar, :born_place_declar,
                                                             :birthday_declar, :registered_in_declar,  :registered_in_address_declar, 
			             :rosary, :rosary_day, :rosary_time, :cemetery, :oven, :reserv_of, 
			             :burial_date, :death_case, :commis_num, :office, :data],
                                    :flowers_attributes => [:id, :kind, :text, :price, :_destroy],
                                    :assistants_attributes => [:id, :name, :_destroy],
                                    :cars_attributes => [:id, :model, :_destroy],
                                    :relative_attributes => [:firstname, :lastname, :phone, :mail, :resident,  :via, :mobile, :fiscal_code,
                                                             :relationship],
                                    :document_attributes => [:document_type, :document_number,
                                                             :document_issued_by, :document_when_issued, :code_fiscale, :issued_by_municipality],
                                    :cemetery_attributes => [:name, :city, :province],
                                    :crematorium_attributes => [:name, :city,:A,:Tel, :Data],
                                    :epigraph_attributes => [:model, :title, :city_title, :dedicated_to, :relatives, :date_vigil,  :time_vigil])
    end

    def _docs_gen
      fields = set_template
      TEMPLATES.each do |template|
        tmp_file = Tempfile.new("#{template[:kind]}", "#{Rails.root}/tmp")
        tmp_file.close
        new_name = "#{File.dirname(tmp_file)}/#{@order.deceased.name}_#{template[:kind]}.docx".upcase
        File.rename(tmp_file, new_name)
        d = Document.find_or_create_by(order: @order, kind: Document.kinds[template[:kind]])
        doc = Docx::Document.open("#{Rails.root}/lib/docx_templates/#{template[:file]}")
        doc.bookmarks.each do |bm|
          doc.bookmarks[bm[0]].insert_text_after(fields[bm[0]])
        end
        file = File.open(new_name)
        doc.save(file)
        d.attach = file
        d.save!
        file.close
      end
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_assistant_fields.html.haml
.row.nested-fields
  .col.s10
    =f.input :name, label: false do
      %i.material-icons.left.prefix account_box
      =f.label :name
      =f.input_field :name, class: 'validate'
  .col.s2
    =link_to_remove_association f, class: 'btn-floating tooltipped', data: { tooltip: 'Delete these flowers' } do
      %i.material-icons.teal.accent-4 delete_forever

app/views/orders/_breadrumbs.html.haml
%nav
  .nav-wrapper.blue-grey
    .col.s12
      = render_breadcrumbs :tag => :a, :separator => ' / '

app/views/orders/_car_fields.html.haml
.row.nested-fields
  .col.s10
    =f.input :model, label: false do
      %i.material-icons.left.prefix account_box
      =f.label :model
      =f.input_field :model, class: 'validate'
  .col.s2
    =link_to_remove_association f, class: 'btn-floating tooltipped', data: { tooltip: 'Delete this car' } do
      %i.material-icons.teal.accent-4 delete_forever

app/views/orders/_fabbuttons.html.haml
#order-fab.fixed-action-btn.row.click-to-toggle.right
  %a.btn-floating.btn-large.red.waves-effect.waves-light
    %i.large.material-icons mode_edit
  %ul
    %li
      = link_to new_order_path, class: 'btn-floating blue-grey darken-2 tooltipped', :data => { :delay => '50', :position => 'left', :tooltip => 'Add new order' } do
        %i.material-icons add
    -if @order
      %li
        = link_to edit_order_path(@order), class: 'btn-floating blue-gray tooltipped', :data => { :delay => '50', :position => 'left', :tooltip => 'Edit current order' } do
          %i.material-icons edit

app/views/orders/_flower_fields.html.haml
.card.nested-fields.col.s4.blue-grey.lighten-5
  .card-content
    .row.valign-wrapper
      = f.input :kind, wrapper_html: { class: 'col s10' }
      .col.s2
        =link_to_remove_association f, class: 'btn-floating right valign right tooltipped', data: { tooltip: 'Delete these flowers' } do
          %i.material-icons.teal.accent-4 delete_forever
    = f.input :price, label: false do
      %i.material-icons.left.prefix euro_symbol
      = f.label :price
      =f.input_field :price
    = f.input :text, as: :text, input_html: { class: 'materialize-textarea' }

app/views/orders/_form.html.haml
= simple_form_for @order, :html => {:multipart => true}, label: false do |f|
  = f.error_notification
  .row
    .col.s12
      %ul.tabs
        %li.tab.col.s0
          =link_to '#general-tab' do
            = t('forms.general')
        %li.tab.col.s0
          =link_to '#relative-tab' do
            = t('forms.relative')
        %li.tab.col.s0
          =link_to '#ceremony-tab' do
            = t('forms.ceremony')         
        %li.tab.col.s0
          =link_to '#burial-tab' do
            = t('forms.burial') 
        %li.tab.col.s0
          =link_to '#crematorium-tab' do
            = t('forms.crematorium')    
        %li.tab.col.s0
          =link_to '#instruments-tab' do
            = t('forms.service')
        %li.tab.col.s0
          =link_to '#flowers-tab' do
            = t('forms.flowers') 
        %li.tab.col.s0
          =link_to '#invoice-tab' do
            = t('forms.invoice')
        %li.tab.col.s0
          =link_to '#epigraph-tab' do
            = t('forms.epigraph')
    #general-tab.col.s12
      =render 'orders/forms/general', f: f
    #crematorium-tab.col.s12
      =render 'orders/forms/crematorium', f: f
    #ceremony-tab.col.s12
      =render 'orders/forms/ceremony', f: f
    #burial-tab.col.s12
      =render 'orders/forms/burial', f: f  
    #relative-tab.col.s12
      =render 'orders/forms/relatives', f: f  
    #instruments-tab.col.s12
      =render 'orders/forms/instruments_flowers', f: f
    #flowers-tab.col.s12
      =render 'orders/forms/flowers', f: f  
    #invoice-tab.col.s12
      =render 'orders/forms/invoice', f: f
    #epigraph-tab.col.s12
      =render 'orders/forms/epigraph', f: f
  .divider
  .section
    .row.center-align
      =f.submit class: 'btn btn-large' do
        %i.material-icons.left save 

app/views/orders/_order_Carta.html.haml
.row
  -orders.each_with_index do |o, i|
    .col.s12.m6
      .card.small
        .card-content
          .card-title
            ="#{o.id}. #{o.deceased.name}" 
            -if o.status == 'active'
              %i.material-icons.teal-text.text-accent-4.tooltipped{data: {tooltip: 'Active'}} done
            -if o.status == 'archived'
              %i.material-icons.blue-grey-text.tooltipped{data: {tooltip: 'Archived'}} archive
            = link_to order_path(o), class: 'right btn-floating waves-effect waves-teal' do
              %i.material-icons open_in_new
          .divider
          .section.row.valign-wrapper
            .col.m4.valign
              = image_tag o.deceased.photo.url(:thumb), class: 'responsive-img center'
            .col.m8.valign
              %p
                = "Funerale: "
                %strong.card-date
                  = " #{o.deceased.funeral_day}"
                = " at "
                %strong.card-place
                  = "#{o.deceased.funeral_place}"
              %p
                = 'Cimitero: '
                %strong.card-cemetey
                  = "#{o.cemetery.name}"
              %p
                = 'Parenti: '
                %strong.card-relative
                  = "#{o.relative.name}"
              %p
                = 'Tel: '
                %strong.card-phone
                  = "#{o.relative.mobile}"
          .divider
          .row
            .col.s12
              %blockquote
                = "Modificato alle "
                %span.card-date
                  ="#{o.edited_at}"
#pagination.center
  =will_paginate orders

app/views/orders/_order_Elenco.html.haml
.card
  %table.table.highlight.centered
    %thead
      %th №
      %th Name
      %th Funeral at
      %th Relative
      %th Mobile number
      %th
    %tbody
    -orders.each_with_index do |o, i|
      %tr
        %td= o.id
        %td= o.deceased.name
        %td= "#{o.deceased.funeral_time} #{o.deceased.funeral_day}"
        %td= o.relative.name
        %td= o.relative.mobile
        %td
          =link_to nil, class: 'dropdown-button btn-flat waves-effect waves-teal', data: { activates: "order-#{o.id}-menu" } do
            %i.material-icons arrow_drop_down
          %ul{:id => "order-#{o.id}-menu", class: 'dropdown-content' }
            %li
              =link_to order_path(o) do
                ='Show'
            %li=link_to 'Edit', edit_order_path(o)
            %li.divider
            %li=link_to 'Delete', order_path(o), method: :delete, confirm: 'Are you sure?', class: 'red-text'
#pagination.center
  =will_paginate orders

app/views/orders/_order_Tabella.html.haml
%ul.collection
  -for o in orders do
    %li.collection-item.avatar
      =image_tag o.deceased.photo(:thumb), class: 'circle', alt: "#{o.deceased.name} photo"
      %span.title="#{o.id}. o.deceased.name"
      %p
        %strong Funeral:
        = "#{o.deceased.funeral_time} #{o.deceased.funeral_day}"
        %br
        %strong cimitero:
        = "#{o.deceased.cemetery_name}"
        %br
        %strong Parente:
        = "#{o.relative.name}, #{o.relative.phone}"
      =link_to order_path(o), class: 'secondary-content btn-large btn-floating transparent z-depth-0' do
        %i.material-icons.blue-grey-text forward
#pagination.center
  =will_paginate orders

app/views/orders/_orders.html.haml
=render "order_#{@view}", orders: @orders

app/views/orders/index.html.haml
.page-header.row.valign-wrapper
  .col.s4
    %h4= "#{params[:archived] ? 'Archived orders' : t('labels.active_orders') }"
  .col.s8.valign
    .col.s12
      =form_tag orders_path, method: :get, id: 'orders_sort', remote: true, class: 'right' do
        %span=t('labels.view_as')
        =select_tag :view, options_for_select([ [t('labels.card'), { class: 'left', 'data-icon': image_url('icons/card.svg') }], [t('labels.table'), { class: 'left', 'data-icon': image_url('icons/grid.svg') }], [t('labels.list'), {  class: 'left', 'data-icon': image_path('icons/list.svg')}]], params[:view]), class: 'icons view'
        %span=t('labels.sorted_by')
        =select_tag :order, options_for_select([t('labels.name'), t('labels.relative'), t('labels.updated')], params[:order]), class: 'order'
        =hidden_field_tag :reverse, params[:reverse]
        =hidden_field_tag :archived, params[:archived]
        =button_tag id: 'order_direction', class: 'btn-floating waves-effect waves-teal', remote: true, type: :button do
          %i.material-icons

=hidden_field_tag :page, params[:page]
#order-panel
  =render "order_#{@view}", orders: @orders

app/views/orders/index.js.haml
$("#order-panel").html("#{escape_javascript(render("order_#{@view}", orders: @orders))}");

app/views/orders/new.html.haml
.row
  .card.col.s10.offset-s1
    .card-content
      %h4
        = 'Nuovo'
      .divider
      = render 'form'

app/views/orders/show.html.haml
#order.row
  #info.card.col.m7
    .card-content
      .card-title
        %span= "#{@order.id}. #{@order.deceased.name} "
        %small= "#{@order.deceased.birthday_year} - #{@order.deceased.death_day_year}"
        -if @order.status == 'active'
          =link_to order_archivate_path(@order), method: :post, remote: true, class: 'right tooltipped', data: {tooltip: 'Archivate', confirm: 'Archive this order?'} do
            %i.material-icons.blue-grey-text archive
        -if @order.status == 'archived'
          =link_to order_activate_path(@order), method: :post, remote: true, class: 'right tooltipped', data: {tooltip: 'Unarchive', confirm: 'Activate this order?'} do
            %i.material-icons.teal-text.text-accent-4 unarchive
      .divider
      .section.row.valign-wrapper
        .col.m8.valign
          %p
            = 'Funerale: '
            %strong= "#{@order.deceased.funeral_place}, #{@order.deceased.funeral_time} #{@order.deceased.funeral_day}"
            %br
            - if @order.cemetery.present?
              = 'Cimitero: '
              %strong= "#{@order.cemetery.province}, #{@order.cemetery.city}, #{@order.cemetery.name}"
              %br
            -if @order.crematorium.present?
              = 'Crematorio: '
              %strong="#{@order.crematorium.city}, #{@order.crematorium.name}"
              %br
            -if @order.relative.present?
              = 'Parente: '
              %strong= "#{@order.relative.name}, "
              %strong="#{@order.relative.mobile}"
        .col.m4.valign
          = image_tag @order.deceased.photo.url(:medium), class: 'photo responsive-img materialboxed'
      .divider
      .section
        .row
          =render 'orders/show/note', order: @order
  .documents.col.m5
    %ul.popout.collapsible{ :data=> { :collapsible => 'expandable'} }
      %li.active
        .collapsible-header.blue-grey.active
          %i.material-icons.left folder_shared
          %strong= 'Documents'
        .collapsible-body
          .collection
            - Order.docs_kinds.keys.each_with_index do |d, i|
              =link_to "#{order_path(@order)}/#{d}", class: 'collection-item', target: '_blank' do
                %span.title
                  = t('labels.'"#{d}")
                %i.material-icons.right file_download