config/routes.rb
Rails.application.routes.draw do
  resources :orders do
    post 'activate' => 'orders#activate', as: :activate
    post 'archive' => 'orders#archivate', as: :archivate

    member do
      get 'check_list' => 'documents#check_list', as: :check_list
      get 'service_list' => 'documents#service_list', as: :service_list
      get 'flowers' => 'documents#flowers', as: :flowers
      get 'cremazione' => 'documents#cremazione', as: :cremazione
      get 'epigrafe' => 'documents#epigrafe', as: :epigrafe
      get 'mod_commis' => 'documents#mod_commis', as: :mod_commis
    end

  end
  resources :documents, only: [:index]
  resources :relatives, as: :contacts, only: [:index]

  root 'orders#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_error_messages_for.html.haml
-if object.errors.present?
  =javascript_tag do
    Materialize.toast("#{msg}", 5000, "error")

app/views/application/_flash_messages.html.haml
-flash.each do |key,msg|
  =javascript_tag do
    Materialize.toast("#{msg}", 5000, "#{key}")
  -#.alert.alert-dismissible{class: "alert-#{key}", role: 'alert'}
  -#  %button.close{ aria: { :label => "Close" }, data: { :dismiss => "alert" }, :type => "button"}
  -#    %span{"aria-hidden" => "true"} ×
  -#  %strong= "#{key}".upcase
  -#  = msg

app/views/application/_footer.html.haml
%footer.page-footer.grey.darken-2
  .container
    .row
      .col.l6.s12
        %h5.white-text 
        %p.grey-text.text-lighten-4
      .col.l4.offset-l2.s12
        %h5.white-text
        %ul
          %li
            %a.grey-text.text-lighten-3{:href => '#!'} 
          %li
            %a.grey-text.text-lighten-3{:href => '#!'} 
  .footer-copyright
    .container
      All rights reserved. Powered by redroids © 2016 Copyright Text

app/views/application/_sidebar.html.haml
%ul#sidenav.side-nav.fixed
  %li.no-padding
    .userView.blue-grey.no-padding
      =link_to '' do
        -#=image_tag 'logo-fre.png', class: 'logo'
  %li.no-padding
    %ul.collapsible.collapsible-accordion{ :data => { :collapsible => 'accordion' } }
      %li.bold
        %a{ class: "collapsible-header waves-effect waves-teal active" }
          %i.material-icons.left list
          = 'Anagrafiche'
        .collapsible-body
          %ul
            %li
              = link_to new_order_path, class: 'waves-effect waves-teal' do
                = 'Nuovo'
                %i.material-icons.right.cyan-text create
            %li.divider
            %li
              = link_to orders_path, class: 'waves-effect waves-teal' do
                = 'Attivi'
                %span.badge
                  = Order.active.size
                %i.material-icons.right.teal-text.text-accent-4 inbox
            %li
              = link_to orders_path(archived: true), class: 'waves-effect waves-teal' do
                ='Archiviati'
                %span.badge
                  = Order.archived.size
                %i.material-icons.right.blue-grey-text archive
    /   %li.bold
    /    %a{ class: "collapsible-header waves-effect waves-teal" }
    /      %i.material-icons contacts
    /      = 'Contatti'
    /    .collapsible-body
    /      %ul
    /        %li
    /          =link_to contacts_path(ricent: true), class: 'waves-effect waves-teal' do
    /            ='Recente'
    /            %span.badge
    /              = Relative.all.size
    /            %i.material-icons.right hourglass_empty
    /        %li
    /          =link_to contacts_path(marked: true), class: 'waves-effect waves-teal' do
    /            ='Segnati'
    /            %span.badge
    /              = Relative.all.marked.size
    /            %i.material-icons.right bookmark  

app/views/application/_topbar.html.haml
#topbar.navbar-fixed
  %nav
    .nav-wrapper.grey.darken-2
      %ul
        -#-if params[:action] == 'show'
        -#  %li
        -#    =link_to , class: 'tooltipped', data: {tooltip: 'Go back'} do
        -#      %i.material-icons.teal-text backspace
        -if ['edit', 'new'].include?(request.original_url.split('/')[-1].split('?')[0])
          %li
            =link_to :back, class: 'tooltipped', data: { tooltip: 'Go back' } do
              %i.material-icons.teal-text.text-accent-1 chevron_left
        -if !['edit', 'new'].include?(request.original_url.split('/')[-1].split('?')[0])
          %li
            =link_to new_order_path, class: 'tooltipped', data: { tooltip: 'Nuovo inserimento' } do
              %i.material-icons.cyan-text.text-accent-1 add_circle
        - if params[:id] and !['edit', 'new'].include?(request.original_url.split('/')[-1].split('?')[0])
          %li
            = link_to edit_order_path(@order), class: 'tooltipped', data: { tooltip: 'Edit this order' } do
              %i.material-icons.teal-text.text-accent-2 mode_edit
          %li
            =link_to order_path(@order), method: :delete, class: 'tooltipped', data: { tooltip: 'Delete this order', confirm: 'Are you sure?' } do
              %i.material-icons.teal-text.text-accent-4 delete
      %ul.right.hide-on-med-and-down
        %li
          = link_to nil, class: 'tooltipped', data: { tooltip: 'Profile settings.' } do
            %i.material-icons account_circle
        %li
          = link_to nil, class: 'tooltipped', data: { tooltip: 'Log out from the app.' } do
            %i.material-icons power_settings_new
      -if !['edit', 'new'].include?(request.original_url.split('/')[-1].split('?')[0])
        =form_tag orders_path(params), method: :get, :id => 'orders_search', class: 'col m4 right', remote: true do
          .input-field
            =text_field_tag :query, params[:query], id: 'search', :required => '', :type => 'search'
            %label{:for => 'search'}
              %i.material-icons search
            %i.material-icons close
      = link_to 'Phoenix', nil, class: 'brand-logo center'

app/views/application/_topnav.html.haml
.topnav.col
  =link_to orders_path, class: 'btn-floating waves-effect waves-light gray-blue' do
    %i.material-icons chevron_left